CREATE TABLE "DEVOPS"."T_BUI_SQL_RULE"
( "ID" NUMBER NOT NULL,
"RULE_ID" VARCHAR2 ( 256 ) NOT NULL,
"RULE_DESC" VARCHAR2 ( 256 ) NOT NULL,
"RULE_TYPE" VARCHAR2 ( 1 ) NOT NULL,
"EFF_FLG" VARCHAR2 ( 1 ) NOT NULL,
"NOD_ID" VARCHAR2 ( 64 ) NOT NULL,
"TM_SMP" VARCHAR2 ( 26 ) NOT NULL,
"REQ_ID" VARCHAR2 ( 64 ) NOT NULL
);
ALTER TABLE "DEVOPS"."T_BUI_SQL_RULE" ADD CONSTRAINT "PK_T_BUI_SQL_RULE" PRIMARY KEY ( "ID" );
COMMENT ON TABLE "DEVOPS"."T_BUI_SQL_RULE" IS 'SQL审核规则配置表';
COMMENT ON COLUMN "DEVOPS"."T_BUI_SQL_RULE"."ID" IS '主键';
COMMENT ON COLUMN "DEVOPS"."T_BUI_SQL_RULE"."RULE_ID" IS '规则编号 每种规则编号固定';
COMMENT ON COLUMN "DEVOPS"."T_BUI_SQL_RULE"."RULE_DESC" IS '规则描述';
COMMENT ON COLUMN "DEVOPS"."T_BUI_SQL_RULE"."RULE_TYPE" IS '规则类型 1-DML 2-DDL create table 3-DDL alter table 4-sequence';
COMMENT ON COLUMN "DEVOPS"."T_BUI_SQL_RULE"."EFF_FLG" IS '生效标志 Y生效 N失效';
COMMENT ON COLUMN "DEVOPS"."T_BUI_SQL_RULE"."NOD_ID" IS '节点id';
COMMENT ON COLUMN "DEVOPS"."T_BUI_SQL_RULE"."TM_SMP" IS '时间戳';
COMMENT ON COLUMN "DEVOPS"."T_BUI_SQL_RULE"."REQ_ID" IS '请求id';
--规则初始化  不能轻易修改内容
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (1,'1','UPDATE语句禁止出现ORDER BY子句','1','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (2,'2','UPDATE语句必须出现WHERE子句','1','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (3,'3','DELETE语句必须出现WHERE子句','1','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (4,'4','DELETE语句禁止出现ORDER BY子句','1','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (5,'5','SELECT语句必须出现WHERE子句','1','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (6,'6','禁止DROP操作','1','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (7,'7','禁止TRUNCATE操作','1','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (8,'8','表必须有注释','2','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (9,'9','字段必须有注释(数据字典名称 | 注释)','2','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (10,'10','非CLOB字段必须NOT NULL','2','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (11,'11','非CLOB字段必须有默认值','2','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (12,'12','表必须有主键(PK_TABLENAME)','2','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (13,'13','字段定义必须符合字典定义','2','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (14,'14','表必须有TM_SMP、NOD_ID、REQ_ID公共字段','2','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (15,'15','表必须有CRE_OPR、UPD_OPR、CRE_TS、UPD_TS公共字段','2','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (16,'16','表名命名不符合规范(T_XXX_*)','2','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (17,'17','字段名命名不符合规范','2','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (18,'18','索引命名不符合规范（UI1_TABLENAME、NI1_TABLENAME）','2','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (19,'19','索引字段超过5个','2','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (20,'20','索引个数超过4个','2','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (21,'21','冗余索引（指该索引可以使用其他索引替代）','2','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (22,'22','索引必须指定TABLESPACE','2','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (23,'9','字段必须有注释(数据字典名称 | 注释)','3','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (24,'10','非CLOB字段必须NOT NULL','3','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (25,'11','非CLOB字段必须有默认值','3','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (26,'13','字段定义必须符合字典定义','3','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (27,'17','字段名命名不符合规范','3','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (28,'18','索引命名不符合规范（UI1_TABLENAME、NI1_TABLENAME）','3','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (29,'19','索引字段超过5个','3','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (30,'22','索引必须指定TABLESPACE','3','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID","RULE_ID","RULE_DESC","RULE_TYPE","EFF_FLG","NOD_ID","TM_SMP","REQ_ID") VALUES (31,'23','SEQUENCE命名不符合规范（S_XX）','4','Y',' ',' ',' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID", "RULE_ID", "RULE_DESC", "RULE_TYPE", "EFF_FLG", "NOD_ID", "TM_SMP", "REQ_ID") VALUES (32, '20', '索引个数超过4个', '3', 'Y', ' ', ' ', ' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID", "RULE_ID", "RULE_DESC", "RULE_TYPE", "EFF_FLG", "NOD_ID", "TM_SMP", "REQ_ID") VALUES (33, '21', '冗余索引', '3', 'Y', ' ', ' ', ' ');
INSERT INTO "DEVOPS"."T_BUI_SQL_RULE"("ID", "RULE_ID", "RULE_DESC", "RULE_TYPE", "EFF_FLG", "NOD_ID", "TM_SMP", "REQ_ID") VALUES ('34', '6', '禁止DROP操作', '3', 'Y', ' ', ' ', ' ');
