/*
 Navicat Premium Data Transfer

 Source Server         : cba-TSDOPS
 Source Server Type    : Oracle
 Source Server Version : 120200
 Source Host           : 10.0.0.6:1521
 Source Schema         : TSDOPS

 Target Server Type    : Oracle
 Target Server Version : 120200
 File Encoding         : 65001

 Date: 20/07/2020 18:35:55
*/


-- ----------------------------
-- Table structure for T_OPS_JOBJNL
-- ----------------------------
DROP TABLE "TSDOPS"."T_OPS_JOBJNL";
CREATE TABLE "TSDOPS"."T_OPS_JOBJNL" (
  "ID" NUMBER(20) VISIBLE NOT NULL ,
  "NAME" VARCHAR2(255 BYTE) VISIBLE NOT NULL ,
  "GRP_NM" VARCHAR2(80 BYTE) VISIBLE DEFAULT 'PUB'  NOT NULL ,
  "URL" VARCHAR2(256 BYTE) VISIBLE DEFAULT ' '  NOT NULL ,
  "CRON" VARCHAR2(80 BYTE) VISIBLE DEFAULT ' '  NOT NULL ,
  "TM_OUT" NUMBER VISIBLE DEFAULT 60  NOT NULL ,
  "REMARK" VARCHAR2(255 BYTE) VISIBLE DEFAULT '' ,
  "BEG_TM" VARCHAR2(14 BYTE) VISIBLE DEFAULT ' ' ,
  "END_TM" VARCHAR2(14 BYTE) VISIBLE DEFAULT ' ' ,
  "STATUS" VARCHAR2(1 BYTE) VISIBLE DEFAULT '0' ,
  "RESULT_MSG" VARCHAR2(2048 BYTE) VISIBLE DEFAULT ' ' ,
  "REQ_ID" VARCHAR2(64 BYTE) VISIBLE DEFAULT '' ,
  "NOD_ID" VARCHAR2(20 BYTE) VISIBLE DEFAULT '' ,
  "TM_SMP" VARCHAR2(14 BYTE) VISIBLE DEFAULT '' ,
  "UPD_OPR" VARCHAR2(10 BYTE) VISIBLE DEFAULT '' 
);
COMMENT ON COLUMN "TSDOPS"."T_OPS_JOBJNL"."ID" IS 'ID编号';
COMMENT ON COLUMN "TSDOPS"."T_OPS_JOBJNL"."NAME" IS '名称';
COMMENT ON COLUMN "TSDOPS"."T_OPS_JOBJNL"."GRP_NM" IS '组名';
COMMENT ON COLUMN "TSDOPS"."T_OPS_JOBJNL"."URL" IS '调用url';
COMMENT ON COLUMN "TSDOPS"."T_OPS_JOBJNL"."CRON" IS '定时表达式';
COMMENT ON COLUMN "TSDOPS"."T_OPS_JOBJNL"."TM_OUT" IS '超时时间';
COMMENT ON COLUMN "TSDOPS"."T_OPS_JOBJNL"."REMARK" IS '备注';
COMMENT ON COLUMN "TSDOPS"."T_OPS_JOBJNL"."BEG_TM" IS '开始时间(yyyyMMddHHmmss)';
COMMENT ON COLUMN "TSDOPS"."T_OPS_JOBJNL"."END_TM" IS '结束时间(yyyyMMddHHmmss)';
COMMENT ON COLUMN "TSDOPS"."T_OPS_JOBJNL"."STATUS" IS '状态(I-开始,S-成功,F-失败,T-超时)';
COMMENT ON COLUMN "TSDOPS"."T_OPS_JOBJNL"."RESULT_MSG" IS '执行结果信息';
COMMENT ON COLUMN "TSDOPS"."T_OPS_JOBJNL"."REQ_ID" IS '交易日志编号';
COMMENT ON COLUMN "TSDOPS"."T_OPS_JOBJNL"."NOD_ID" IS '应用节点名称';
COMMENT ON COLUMN "TSDOPS"."T_OPS_JOBJNL"."TM_SMP" IS '时间戳';
COMMENT ON COLUMN "TSDOPS"."T_OPS_JOBJNL"."UPD_OPR" IS '操作员';
COMMENT ON TABLE "TSDOPS"."T_OPS_JOBJNL" IS '定时任务流水表';

-- ----------------------------
-- Primary Key structure for table T_OPS_JOBJNL
-- ----------------------------
ALTER TABLE "TSDOPS"."T_OPS_JOBJNL" ADD CONSTRAINT "PK_T_OPS_JOBJNL" PRIMARY KEY ("ID");


-- ----------------------------
-- Indexes structure for table T_OPS_JOBJNL
-- ----------------------------
CREATE INDEX "TSDOPS"."N11_T_OPS_JOBJNL"
  ON "TSDOPS"."T_OPS_JOBJNL" ("NAME" ASC)
  LOGGING
  TABLESPACE "TBS_TSDOPS_DATA"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 8388608 
  NEXT 8388608 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
